config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  devise_for :admins, controllers: { 
    sessions: 'admins/sessions'
  }
  namespace :admins do
    get 'dashboard', to: 'dashboard#index'
    get 'daily_statistic', to: 'admins/daily_statistic'
    get 'weekly_statistic', to: 'admins/weekly_statistic'
    resources :userslists, only: [:index, :show]
    resources :activity_tracking, only:[:show, :index]
  end

  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
 
  resources :bookings, except:[:derstroy] do
    member do
      patch :cancel
      patch :restore
    end
  end
  get '/home', to: 'pages#home'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  has_many :activity_trackings
  enum status: { pending: 0, paid: 1, canceled: 2 }
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: [:show, :edit, :update, :cancel, :restore]

  def index
    @bookings = Booking.all
    first_visit = ActivityTracking.user_activity_exists?(current_user.id, 'Visit', 'first visit booking page')

    if first_visit
      track_activity('Visit', 'visit booking page')
    else
      track_activity('Visit', 'first visit booking page')
    end
  end

  def new
    @booking = Booking.new
    track_activity('Visit', 'visit booking detail')
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.booking_period = calculate_booking_period(current_user)
    p @booking.booking_period 
    if @booking.save
      track_activity('Submit', 'submit booking', @booking )
      redirect_to bookings_path, notice:'訂購成功'
    end
  end

  def cancel
    if @booking.update(status: :canceled)
      track_activity('Cancel', 'cancel booking', @booking)
      redirect_to bookings_path, notice: '預訂已取消'
    end
  end

  def restore
    if @booking.update(status: :pending)
      track_activity('Restore', 'restore canceled booking', @booking)
      redirect_to bookings_path, notice: '已恢復預訂'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :status, :content, :user_id, :booking_period)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def calculate_booking_period(user)
    first_visit_time = ActivityTracking.find_by(user: user, action_params: 'first visit booking page').timestamp
    submit_time = Time.now
    (submit_time - first_visit_time).to_i
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/index.html.erb
<h1 class="h1">Booking Page</h1>

<%= link_to 'Item1', new_booking_path, class:'text-blue-400 m-20 text-3xl' %>

<% if current_user.bookings.any? %>
  <h2 class="font-bold m-5">已預訂的項目</h2>
  <ul>
    <% current_user.bookings.each do |booking| %>
    <li class="m-5">
      <p class='mx-5 text-2xl'>
        <%= booking.content %>
      </p>
      <%= booking.status %>
      <%= booking.created_at.strftime('%F') %>
      <% if booking.canceled? %>
        <%= link_to 'Restore', restore_booking_path(booking), data: {turbo_method: 'patch'}, class: 'text-blue-400 mx-5' %>
      <% else %>
        <%= link_to 'Cancel', cancel_booking_path(booking), data: {turbo_method: 'patch' , turbo_confirm: '確定要取消此預定嗎?'}, class: 'text-blue-400 mx-5' %>
      <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/bookings/new.html.erb
<h1 class="h1">Details</h1>
<%= form_with(model: @booking, local: true, data: { turbo: false }) do |f| %>

  <div>
    <%= f.hidden_field :user_id, value: current_user.id %>

    <%= f.label :content, '不加辣' %>
    <%= f.radio_button :content, '不加辣' %>

    <%= f.label :content, '加辣' %>
    <%= f.radio_button :content, '加辣' %>
  </div>

  <div>
    <%= f.submit 'Booking', class:'text-blue-500 hover:text-blue-300 cursor-pointer' %>
  </div>

<% end %>