config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  devise_for :admins, controllers: { 
    sessions: 'admins/sessions'
  }
  namespace :admins do
    get 'dashboard', to: 'dashboard#index'
    get 'daily_statistic', to: 'admins/daily_statistic'
    get 'weekly_statistic', to: 'admins/weekly_statistic'
    resources :userslists, only: [:index, :show]
    resources :activity_tracking, only:[:show, :index]
  end

  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
 
  resources :bookings, except:[:derstroy] do
    member do
      patch :cancel
      patch :restore
    end
  end
  get '/home', to: 'pages#home'
end

app/models/activity_tracking.rb
class ActivityTracking < ApplicationRecord
  belongs_to :user
  belongs_to :booking, optional: true
  validate :valid_action_type

  VALID_ACTION_TYPES = [
    'Visit',
    'Login',
    'Logout',
    'Sign_up',
    'Reset_password',
    'Submit',
    'Cancel',
    'Restore'
   ].freeze

  private

  def valid_action_type
    errors.add(:action_type, 'is not valid') unless VALID_ACTION_TYPES.include?(action_type)
  end
  
  def self.user_activity_exists?(user_id, action, action_params)
    where(user_id: user_id, action_type: action, action_params: action_params).exists?
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  has_many :activity_trackings
  enum status: { pending: 0, paid: 1, canceled: 2 }
end

app/models/daily_statistic.rb
class DailyStatistic < ApplicationRecord
  validates :date, presence: true, uniqueness: true

  def self.booking_period(user_id)
    first_visit = ActivityTracking.find_by(user_id: user_id, action_type: 'first visit booking page')
    booking_submit = ActivityTracking.find_by(user_id: user_id, action_type: 'submit booking')

    return nil if first_visit.nil? || booking_submit.nil?

    booking_submit.timestamp - first_visit.timestamp
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :activity_trackings

  validates :name, presence: true, uniqueness: true

  def record_first_activity!(type, params)
    unless ActivityTracking.exists?(user: self, action_type: type, action_params: params)
      ActivityTracking.create(user: self, action_type: type, action_params: params, timestamp: Time.current)
    end
  end

end

app/models/weekly_statistic.rb
class WeeklyStatistic < ApplicationRecord
end

app/controllers/activity_trackings_controller.rb
class ActivityTrackingsController < ApplicationController
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!
  layout "admins"

  def daily_statistic
    @daily_statistics = DailyStatistic.all.order(date: :desc)
  end

  def weekly_statistic
    @weekly_statistics = WeeklyStatistic.all.order(start_date: :desc)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def track_activity(action_type, action_params = nil, booking = nil)
    ActivityTracking.create(
      user: current_user,
      action_type: action_type,
      action_params: action_params,
      timestamp: Time.now,
      booking: booking
    )
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: [:show, :edit, :update, :cancel, :restore]

  def index
    @bookings = Booking.all
    first_visit = ActivityTracking.user_activity_exists?(current_user.id, 'Visit', 'first visit booking page')

    if first_visit
      track_activity('Visit', 'visit booking page')
    else
      track_activity('Visit', 'first visit booking page')
    end
  end

  def new
    @booking = Booking.new
    track_activity('Visit', 'visit booking detail')
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.booking_period = calculate_booking_period(current_user)
    p @booking.booking_period 
    if @booking.save
      track_activity('Submit', 'submit booking', @booking )
      redirect_to bookings_path, notice:'訂購成功'
    end
  end

  def cancel
    if @booking.update(status: :canceled)
      track_activity('Cancel', 'cancel booking', @booking)
      redirect_to bookings_path, notice: '預訂已取消'
    end
  end

  def restore
    if @booking.update(status: :pending)
      track_activity('Restore', 'restore canceled booking', @booking)
      redirect_to bookings_path, notice: '已恢復預訂'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :status, :content, :user_id, :booking_period)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def calculate_booking_period(user)
    first_visit_time = ActivityTracking.find_by(user: user, action_params: 'first visit booking page').timestamp
    submit_time = Time.now
    (submit_time - first_visit_time).to_i
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if current_user
      track_activity('Visit', 'visit home page')
    end
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/activity_trackings_helper.rb
module ActivityTrackingsHelper
end

app/helpers/admins/userslists_helper.rb
module Admins::UserslistsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admins/daily_statistic.html.erb
<h1 class="h1">Daily Statistics</h1>
<div class="grid grid-cols-6 gap-3 border-2">
  <div class="border-solid border-r-2 text-center">日期</div>
  <div class="border-solid border-r-2 text-center">日活躍用戶數</div>
  <div class="border-solid border-r-2 text-center">每日預訂數量</div>
  <div class="border-solid border-r-2 text-center">日平均用戶預訂時長</div>
  <div class="border-solid border-r-2 text-center">每日99%用戶預訂期</div>
  <div class="text-center">每日最大用戶預訂期限</div>
</div>

<% @daily_statistics.each do |statistic| %>
  <div class="grid grid-cols-6 gap-3 border-2">
    <div class="border-solid border-r-2 text-center"><%= statistic.date %></div>
    <div class="border-solid border-r-2 text-center"><%= statistic.active_users %></div>
    <div class="border-solid border-r-2 text-center"><%= statistic.booking_number %></div>
    <div class="border-solid border-r-2 text-center"><%= statistic.average_booking_period %></div>
    <div class="border-solid border-r-2 text-center"><%= statistic.percentile_99th_booking_period %></div>
    <div class="text-center"><%= statistic.maximum_booking_period %></div>
  </div>
<% end %>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/admins/weekly_statistic.html.erb
<h1 class="h1">Weekly Statistics</h1>
<div class="grid grid-cols-4 gap-3 border-2">
  <div class="border-solid border-r-2 text-center">年</div>
  <div class="border-solid border-r-2 text-center">日期</div>
  <div class="border-solid border-r-2 text-center">周活躍用戶</div>
  <div class="border-solid border-r-2 text-center">周預定數量</div>
</div>

<% @weekly_statistics.each do |statistic| %>
  <div class="grid grid-cols-4 gap-3 border-2">
    <div class="border-solid border-r-2 text-center"><%= statistic.start_date.strftime("%Y") %></div>
    <div class="border-solid border-r-2 text-center"><%= statistic.start_date.strftime("%m/%d") %> - <%= statistic.end_date.strftime("%m/%d") %></div>
    <div class="border-solid border-r-2 text-center"><%= statistic.active_users %></div>
    <div class="border-solid border-r-2 text-center"><%= statistic.booking_number %></div>
  </div>
<% end %>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserTraking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <nav class="flex justify-between p-5 ">
      <div>
        <% if current_admin %>
          <%= link_to 'Dash Board', admins_dashboard_path %>
          <%= link_to('登出', destroy_admin_session_path, class:'mx-3', data: { turbo_method: 'delete' }) %>
        <% end %>
      </div>
      <div>
        <%= link_to 'home', root_path, class:'mx-3' %>
      </div>
    </nav>
  </head>

  <body>
    <%= flash[:notice] %>
    <%= flash[:alert] %>

    <main class="container mx-auto mt-8 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserTraking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <nav class="flex justify-between p-5 ">
      <div>
        <% if current_user %>
          <%= link_to('登出', destroy_user_session_path, data: { turbo_method: 'delete' }) %> |
          <%= link_to('修改密碼', edit_registration_path(:user)) %>
        <% else %>
          <%= link_to('註冊', new_registration_path(:user)) %> |
          <%= link_to('登入', new_session_path(:user)) %>
        <% end %>

        <%= link_to 'home', root_path, class:'mx-3' %>
      </div>
      <div>
        <% if current_admin %>
        <% else %>
          <%= link_to('後台登入', new_session_path(:admin)) %>
        <% end %>
      </div>
    </nav>
  </head>

  <body>
    <%= flash[:notice] %>
    <%= flash[:alert] %>
    <main class="container m-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class="h1"> Home </h1>
<%= link_to 'Booking page', bookings_path, class:'text-blue-400 m-20 text-xl' %>